### ISSUE TITLE
Task no longer works; gives 404 error

### ISSUE THREAD

**Issue by deadlydog** [mmajcica/retain-release#5]
It seems this task stopped working sometime in 2019. It used to work last year, but this year anytime we've tried to use it we get a 404 error. Here's the task output:

```
2019-10-31T15:19:01.9841463Z ##[section]Starting: Retain the Build and Release forever
2019-10-31T15:19:01.9933339Z ==============================================================================
2019-10-31T15:19:01.9933431Z Task         : Set Retention forever on a Build Release
2019-10-31T15:19:01.9933509Z Description  : Set Retention forever on a Build Release
2019-10-31T15:19:01.9933566Z Version      : 1.0.10
2019-10-31T15:19:01.9933639Z Author       : Haribabu, Bavanari
2019-10-31T15:19:01.9933707Z Help         : 
2019-10-31T15:19:01.9933778Z ==============================================================================
2019-10-31T15:19:01.9937961Z ##[warning]Task 'RetentionTask' (1.0.10) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib
2019-10-31T15:19:01.9938653Z Preparing task execution handler.
2019-10-31T15:19:02.1379607Z Executing the powershell script: C:\Builds\_work\_tasks\RetentionTask_7b42ca94-dc22-43dd-8b65-fcbf854b6b78\1.0.10\BuildReleaseRetentionTask.ps1
2019-10-31T15:19:02.8215956Z ##[error]System.Net.WebException: The remote server returned an error: (404) Not Found.
2019-10-31T15:19:02.8216391Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2019-10-31T15:19:02.8216542Z    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2019-10-31T15:19:02.8381381Z ##[error]PowerShell script completed with 1 errors.
2019-10-31T15:19:02.8382092Z ##[section]Finishing: Retain the Build and Release forever
```

**Comment by mmajcica** [comment]
This is not the right projects, seem that this task is made by Haribabu, Bavanari, not by me.
My extension is the following https://marketplace.visualstudio.com/items?itemName=mmajcica.retain-release

Cheers

**Comment by deadlydog** [comment]
Ok, yeah thanks. Looking into it further it seemed that the extension was no longer installed in our Azure DevOps, but the tasks were still in some of our release definitions, which is very strange. I'm guessing he pulled his extension from the marketplace. I installed your extension though and tested using it instead and it seems to work properly. Thanks!
